spring:
  datasource:
    name: mysql-trade
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.11.133:3306/trade?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: customer
    druid:
      initial-size: 3
      filter:
        stat:
          enabled: true
      stat-view-servlet:
        enabled: true
        login-username: customer
        allow: 127.0.0.1
